version: "3.9"
services:
  server:
    build: ./apps/server
    environment:
      - PORT=8787
    volumes:
      - ./apps/server:/app
    ports:
      - "8787:8787"
  web:
    working_dir: /app
    image: node:20
    command: sh -c "npm i -g pnpm && pnpm i && pnpm dev"
    volumes:
      - ./apps/web:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API=http://localhost:8787
